export const KEYWORDS = [
  "MentorHub",
  "mentorship",
  "mentoring",
  "skills development",
  "career growth",
  "professional development",
  "networking",
  "learning",
  "knowledge sharing",
  "community",
  "personal growth",
  "education",
  "online platform",
  "mentorship platform",
  "mentorship community",
  "mentorship network",
  "mentorship program",
  "mentorship opportunities",
  "mentorship resources",
  "mentorship connections",
  "mentorship relationships",
  "mentorship success",
  "mentorship stories",
  "mentorship impact",
  "mentorship benefits",
  "mentorship challenges",
  "mentorship tips",
].map((keyword) => keyword.toLowerCase());
